In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
raw_data = pd.read_csv('nba_coach_of_the_year.csv')

In [ ]:
#コーチオブザイヤーを受賞した（１）かしてない（０）か＝y
#その他＝x

raw_data = raw_data.drop('season', axis=1)
x = raw_data.iloc[:, 2:-1].values
y = raw_data.iloc[:, -1].values

In [ ]:
#受賞したデータとしてないデータの比率が（ほぼ）1:29なので、受賞したデータを増やしてバランスをよくする

from imblearn.over_sampling import RandomOverSampler

sampler = RandomOverSampler(random_state=0)
x_resampled, y_resampled = sampler.fit_resample(x, y)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x_resampled)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_resampled, test_size=0.2, random_state=42)

In [ ]:
import tensorflow as tf

ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units='1', activation='sigmoid'))

ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

ann.fit(x_train, y_train, batch_size=32, epochs=70)

Epoch 1/70
47/47 [==============================] - 1s 4ms/step - loss: 0.6060 - accuracy: 0.7586
Epoch 2/70
47/47 [==============================] - 0s 4ms/step - loss: 0.5076 - accuracy: 0.8478
Epoch 3/70
47/47 [==============================] - 0s 3ms/step - loss: 0.4168 - accuracy: 0.8659
Epoch 4/70
47/47 [==============================] - 0s 4ms/step - loss: 0.3790 - accuracy: 0.8719
Epoch 5/70
47/47 [==============================] - 0s 4ms/step - loss: 0.3668 - accuracy: 0.8766
Epoch 6/70
47/47 [==============================] - 0s 4ms/step - loss: 0.3587 - accuracy: 0.8773
Epoch 7/70
47/47 [==============================] - 0s 4ms/step - loss: 0.3515 - accuracy: 0.8833
Epoch 8/70
47/47 [==============================] - 0s 4ms/step - loss: 0.3463 - accuracy: 0.8860
Epoch 9/70
47/47 [==============================] - 0s 4ms/step - loss: 0.3418 - accuracy: 0.8880
Epoch 10/70
47/47 [==============================] - 0s 4ms/step - loss: 0.3370 - accuracy: 0.8893
Epoch 11/70
47/47 [

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

cm = confusion_matrix(y_test, y_pred)

print(cm)
accuracy_score(y_pred, y_test)

[[179  12]
 [ 10 172]]


0.9410187667560321

In [ ]:
#今シーズンのCOYのノミネートされたコーチが在籍する３チーム
#上からMIA、PHX、MEM

nominees = np.array([
                     [1, 0.646, 5, 0.09, 4.7, 17, 0, 0, 1],
                     [1, 0.78, 1, 0.072, -3.3, 18.7, 1, 0, 0],
                     [2, 0.683, 7, 0.155, -7.1, 15.27, 0, 1, 0]
])

In [ ]:
nom_scaled = scaler.transform(nominees)

In [ ]:
print(ann.predict(nom_scaled))

[[0.00536469]
 [0.03395596]
 [0.999915  ]]


In [ ]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression()

In [ ]:
y_pred = classifier.predict(x_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[160  31]
 [ 19 163]]


0.8659517426273459

In [ ]:
print(classifier.coef_)

[[-1.31396203  0.16964305 -1.00674782  2.40721404 -0.05094544 -0.09475517
   0.21091315  0.02050081 -0.14271207]]
